# Site settings
title: bkbilly's website
email: vasilisskoulis@gmail.com
url: https://bkbilly.github.io
description: "Portofolio of Vasilis Koulis."
keywords: "portofolio, bkbilly, vasilis, koulis, projects"
skills: "Software Engineer"
meta_author: Koulis Vasilis

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9c6816 #18bc9c #80B3FF
  primary-rgb: "255,182,66" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Vasilis Koulis
  location: Location
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# https://fontawesome.com
social:
  - title: linkedin
    url: https://www.linkedin.com/in/bkbilly
  - title: github
    url: https://github.com/bkbilly
  - title: github
    url: https://gist.github.com/bkbilly
  - title: twitter
    url: https://twitter.com/bkbilly
  - title: unity
    url: https://www.thingiverse.com/bkbilly
  # - title: bitbucket
  #   url: http://bitbucket.org/bkbilly

# Postal address (add as many lines as necessary)
address:
  - line: Lincoln, UK
  - line: Athens, Greece

# Credits content
credits: '<a href="mailto:vasilisskoulis@gmail.com">vasilisskoulis@gmail.com</a>'

# Build settings
markdown: kramdown
permalink: pretty
